abstract: "Documentation/Abstracts/*.markdown"
author: "kibigo!"
author_url: "https://go.KIBI.family/About/#me"
clean: true
copyright: |-
  The Source Code Form from which this documentation was generated is subject to the terms of the [_Mozilla Public License, version 2.0_](https://mozilla.org/MPL/2.0/).
documentation: "Documentation/*.markdown"
github_file_prefix: "https://github.com/marrus-sh/Nib-Core/blob/current"
github_url: "https://github.com/marrus-sh/Nib-Core"
head: |-
  <style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@200;600&family=Nanum+Gothic+Coding:wght@400;700&display=swap');
  body{ Color: #DEDBD9; Background: #1F1A14; Font: 200 1REM / 1.7 Inter, Sans-Serif }
  h1,h2,h3,h4,h5{ Color: #FAF8F7; Font-Weight: 600 }
  h6{ Color: Inherit; Font-Weight: 600 }
  blockquote{ Border-Color: #F56E97; Color: #FAF8F7 }
  a{ Color: #DEDBD9; Font-Weight: Bold }
  a:Hover{ Color: #FAF8F7 }
  a.discouraged{ Font-Weight: Normal }
  table{ Color: #FAF8F7; Background: #302F2B }
  tr:Nth-Child(2N){ Background-Color: #57534C }
  th,td{ Border-Color: #B8B3B0 }
  pre{ Color: #FAF8F7; Background: #302F2B; Font-Family: "Nanum Gothic Coding", Monospace }
  code{ Font-Family: "Nanum Gothic Coding", Monospace }
  .item-container p>code,
  .item-container li>code,
  .top-matter p>code,
  .top-matter li>code{ Color: #FAF8F7; Background: #302F2B }
  .header{ Color: #FAF8F7; Background: #4B2DF7 }
  a.header-link{ Color: Inherit }
  .breadcrumbs{ Border-Color: #75706A; Color: #1F1A14; Background: #F56E97 }
  a.breadcrumb{ Color: Inherit }
  @media (Min-Width: 768PX){
  	.navigation{ Border-Color: #75706A; Color: #DEDBD9; Background: #302F2B } }
  .nav-group-name{ Border-Color: #75706A }
  .nav-group-name-link{ Color: #F56E97 }
  .nav-group-task-link{ Color: Inherit }
  .nav-group-task-link:Hover{ Color: #F56E97 }
  .section{ Border-Color: #75706A }
  .section-name{ Color: #F56E97 }
  .task-group-section{ Border-Color: #75706A }
  .pointer-container{ Border-Color: #B01C1C }
  .pointer{ Border-Color: #B01C1C; Color: #FAF8F7; Background: #302F2B }
  .height-container .section{ Border-Color: #F56E97; Color: #FAF8F7; Background: #302F2B }
  .aside,
  .language{ Border-Color: #F56E97; Color: #B8B3B0; Background: #1F1A14 }
  .aside .aside-title,
  .language .aside-title{ Color: #F56E97 }
  .aside-warning,
  .aside-deprecated,
  .aside-unavailable{ Border-Color: #EB9100 }
  .aside-warning .aside-title,
  .aside-deprecated .aside-title,
  .aside-unavailable .aside-title{ Color: #FAE13E }
  .graybox{ Background: #302F2B }
  .graybox td{ Border-Color: #75706A }
  .graybox td:Nth-Child(2N + 1){ Background: #1F1A14 }
  .footer{ Color: #FAF8F7; Background: #4B2DF7 }
  .footer a{ Color: Inherit }
  .highlight a:Not(:Hover){ Color: Inherit; Font-Weight: Inherit; Text-Decoration: Underline; Text-Decoration-Style: Wavy }
  .highlight .c{ Color: #B8B3B0; Font-Style: Inherit } /* Comment */
  .highlight .err{ Color: #FAF8F7; Background: #B01C1C } /* Error */
  .highlight .k{ Color: #F56E97 } /* Keyword */
  .highlight .o{ Color: Inherit; Font-Weight: Inherit } /* Operator */
  .highlight .cm{ Color: #B8B3B0; Font-Style: Inherit } /* Comment.Multiline */
  .highlight .cp{ Color: #B8B3B0; Font-Style: Normal; Font-Weight: Bold } /* Comment.Preproc */
  .highlight .c1{ Color: #B8B3B0; Font-Style: Inherit } /* Comment.Single */
  .highlight .cs{ Color: #B8B3B0; Font-Family: Inter, Sans-Serif; Font-Style: Inherit; Font-Weight: Inherit } /* Comment.Special */
  .highlight .gd{ Color: #FAF8F7; Background: #D15919 } /* Generic.Deleted */
  .highlight .gd .x{ Color: #EB9100; Background: #1F1A14 } /* Generic.Deleted.Specific */
  .highlight .ge{ Color: Inherit; Font-Style: Inherit; Font-Weight: Bold } /* Generic.Emph */
  .highlight .gr{ Color: #EB9100 } /* Generic.Error */
  .highlight .gh{ Color: #FAF8F7 } /* Generic.Heading */
  .highlight .gi{ Color: #FAF8F7; Background: #4B2DF7 } /* Generic.Inserted */
  .highlight .gi .x{ Color: #F56E97; Background: #1AACEB } /* Generic.Inserted.Specific */
  .highlight .go{ Color: #B8B3B0 } /* Generic.Output */
  .highlight .gp{ Color: #DEDBD9 } /* Generic.Prompt */
  .highlight .gs{ Color: #FAF8F7; Font-Weight: Bold } /* Generic.Strong */
  .highlight .gu{ Color: #DEDBD9 } /* Generic.Subheading */
  .highlight .gt{ Color: #F56E97 } /* Generic.Traceback */
  .highlight .kc{ Color: #1AACEB } /* Keyword.Constant */
  .highlight .kd{ Color: #F56E97 } /* Keyword.Declaration */
  .highlight .kp{ Color: #FAE13E } /* Keyword.Pseudo */
  .highlight .kr{ Color: #F56E97 } /* Keyword.Reserved */
  .highlight .kt{ Color: #1AACEB; Font-Weight: Bold } /* Keyword.Type */
  .highlight .m{ Color: #1AACEB } /* Literal.Number */
  .highlight .s{ Color: #FAE13E } /* Literal.String */
  .highlight .na { Color: #EB9100 } /* Name.Attribute */
  .highlight .nb { Color: #F56E97 } /* Name.Builtin */
  .highlight .nc { Color: #1AACEB } /* Name.Class */
  .highlight .no { Color: #FAF8F7 } /* Name.Constant */
  .highlight .ni { Color: #1AACEB } /* Name.Entity */
  .highlight .ne { Color: #F56E97; Font-Weight: Bold } /* Name.Exception */
  .highlight .nf { Color: #1AACEB } /* Name.Function */
  .highlight .nn { Color: #FAF8F7 } /* Name.Namespace */
  .highlight .nt { Color: #FAE13E } /* Name.Tag */
  .highlight .nv { Color: #FAF8F7 } /* Name.Variable */
  .highlight .ow { Color: #FAF8F7; Font-Weight: Inherit } /* Operator.Word */
  .highlight .w { Color: #75706A } /* Text.Whitespace */
  .highlight .mf { Color: #1AACEB } /* Literal.Number.Float */
  .highlight .mh { Color: #1AACEB } /* Literal.Number.Hex */
  .highlight .mi { Color: #1AACEB } /* Literal.Number.Integer */
  .highlight .mo { Color: #1AACEB } /* Literal.Number.Oct */
  .highlight .sb { Color: #FAE13E } /* Literal.String.Backtick */
  .highlight .sc { Color: #FAE13E } /* Literal.String.Char */
  .highlight .sd { Color: #FAE13E } /* Literal.String.Doc */
  .highlight .s2 { Color: #FAE13E } /* Literal.String.Double */
  .highlight .se { Color: #FAE13E } /* Literal.String.Escape */
  .highlight .sh { Color: #FAE13E } /* Literal.String.Heredoc */
  .highlight .si { Color: #FAE13E } /* Literal.String.Interpol */
  .highlight .sx { Color: #FAE13E } /* Literal.String.Other */
  .highlight .sr { Color: #EB9100 } /* Literal.String.Regex */
  .highlight .s1 { Color: #FAE13E } /* Literal.String.Single */
  .highlight .ss { Color: #EB9100 } /* Literal.String.Symbol */
  .highlight .bp { Color: #FAE13E } /* Name.Builtin.Pseudo */
  .highlight .vc { Color: #1AACEB } /* Name.Variable.Class */
  .highlight .vg { Color: #FAF8F7 } /* Name.Variable.Global */
  .highlight .vi { Color: #FAF8F7 } /* Name.Variable.Instance */
  .highlight .il { Color: #1AACEB } /* Literal.Number.Integer.Long */
  </style>
module: "Core"
module_version: "0.2.0-development"
output: .jazzy-docs
root_url: "https://go.KIBI.family/Nib-Core/"
separate_global_declarations: true
swift_build_tool: spm
swift_version: 5.4
theme: fullwidth
title: "Nib Core 0·2"
